
CC:=gcc

CPPFLAGS:=
CXXFLAGS:=-g -std=c++17
LDFLAGS:=

# SRCS:=Common.cpp

.PHONY: all clean

all: Common DestructorConstructor

Common: Common.cpp

DestructorConstructor: DestructorConstructor.cpp

clean:
	rm -f Common
	rm -f DestructorConstructor
	rm -rf Common.dSYM
	rm -rf DestructorConstructor.dSYM


